-- =====================================================================
-- SQL Performance & Tuning (SPT) - core schema - SQLITE (local dev only)
--
-- Structurally identical to db/migration/oracle/V1__core_schema.sql.
-- Keep both files in sync: every Oracle migration needs a SQLite twin
-- with the same version number.
-- Type mapping: NUMBER(19) -> INTEGER, NUMBER(p,s) -> NUMERIC,
-- VARCHAR2/CLOB -> TEXT, TIMESTAMP -> TIMESTAMP (stored by the driver).
-- =====================================================================

CREATE TABLE SPT_DATA_SOURCE (
    ID              INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME            TEXT    NOT NULL,
    SOURCE_TYPE     TEXT    NOT NULL CHECK (SOURCE_TYPE IN ('ORACLE', 'IMPALA', 'GENERIC_JDBC')),
    SQL_ENGINE      TEXT    NOT NULL DEFAULT 'IMPALA',
    JDBC_URL        TEXT    NOT NULL,
    DRIVER_CLASS    TEXT,
    USERNAME        TEXT,
    PASSWORD_REF    TEXT,
    LOG_QUERY       TEXT    NOT NULL,
    FETCH_SIZE      INTEGER NOT NULL DEFAULT 1000,
    LAST_WATERMARK  TIMESTAMP,
    ACTIVE          INTEGER NOT NULL DEFAULT 1 CHECK (ACTIVE IN (0, 1)),
    DESCRIPTION     TEXT,
    CREATED_AT      TIMESTAMP NOT NULL,
    CREATED_BY      TEXT,
    UPDATED_AT      TIMESTAMP,
    UPDATED_BY      TEXT,
    VERSION         INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT UK_SPT_DATA_SOURCE_NAME UNIQUE (NAME)
);

CREATE TABLE SPT_INGESTION_BATCH (
    ID              INTEGER PRIMARY KEY AUTOINCREMENT,
    SOURCE_KIND     TEXT    NOT NULL CHECK (SOURCE_KIND IN ('CSV', 'EXCEL', 'JDBC')),
    DATA_SOURCE_ID  INTEGER REFERENCES SPT_DATA_SOURCE (ID),
    SOURCE_NAME     TEXT,
    SQL_ENGINE      TEXT    NOT NULL,
    STATUS          TEXT    NOT NULL CHECK (STATUS IN ('RUNNING', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'FAILED')),
    ROWS_READ       INTEGER NOT NULL DEFAULT 0,
    ROWS_LOADED     INTEGER NOT NULL DEFAULT 0,
    ROWS_REJECTED   INTEGER NOT NULL DEFAULT 0,
    GROUPS_AFFECTED INTEGER NOT NULL DEFAULT 0,
    MESSAGE         TEXT,
    STARTED_AT      TIMESTAMP NOT NULL,
    COMPLETED_AT    TIMESTAMP,
    CREATED_BY      TEXT
);

CREATE TABLE SPT_QUERY_GROUP (
    ID                     INTEGER PRIMARY KEY AUTOINCREMENT,
    FINGERPRINT            TEXT    NOT NULL,
    SQL_ENGINE             TEXT    NOT NULL,
    GROUP_SIZE             INTEGER NOT NULL DEFAULT 0,
    DISTINCT_USERS         INTEGER NOT NULL DEFAULT 0,
    USER_IDS               TEXT,
    DURATION_COUNT         INTEGER NOT NULL DEFAULT 0,
    AVG_DURATION_MINUTES   NUMERIC,
    MIN_DURATION_MINUTES   NUMERIC,
    MAX_DURATION_MINUTES   NUMERIC,
    TOTAL_DURATION_MINUTES NUMERIC,
    ERROR_COUNT            INTEGER NOT NULL DEFAULT 0,
    SAMPLE_LOG_ID          INTEGER,
    SAMPLE_QUERY_SEQ_ID    INTEGER,
    SAMPLE_QUERY           TEXT,
    NORMALIZED_QUERY       TEXT,
    ROW_INDICES            TEXT,
    FIRST_SEEN             TIMESTAMP,
    LAST_SEEN              TIMESTAMP,
    CREATED_AT             TIMESTAMP NOT NULL,
    UPDATED_AT             TIMESTAMP,
    VERSION                INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT UK_SPT_GROUP_FP UNIQUE (SQL_ENGINE, FINGERPRINT)
);
CREATE INDEX IX_SPT_GROUP_TOTAL_DUR ON SPT_QUERY_GROUP (TOTAL_DURATION_MINUTES);

CREATE TABLE SPT_QUERY_LOG (
    ID                INTEGER PRIMARY KEY AUTOINCREMENT,
    BATCH_ID          INTEGER NOT NULL REFERENCES SPT_INGESTION_BATCH (ID),
    SEQ_ID            INTEGER,
    EXECUTED_QUERY    TEXT,
    USER_QUERY        TEXT,
    ERROR_CODE        TEXT,
    ERROR_CATEGORY    TEXT,
    ERROR_MESSAGE     TEXT,
    USER_ID           TEXT,
    START_TIME        TIMESTAMP,
    END_TIME          TIMESTAMP,
    DURATION_MINUTES  NUMERIC,
    SQL_ENGINE        TEXT    NOT NULL,
    FINGERPRINT       TEXT,
    GROUP_ID          INTEGER REFERENCES SPT_QUERY_GROUP (ID),
    CREATED_AT        TIMESTAMP NOT NULL
);
CREATE INDEX IX_SPT_LOG_GROUP ON SPT_QUERY_LOG (GROUP_ID);
CREATE INDEX IX_SPT_LOG_FP ON SPT_QUERY_LOG (SQL_ENGINE, FINGERPRINT);
CREATE INDEX IX_SPT_LOG_BATCH ON SPT_QUERY_LOG (BATCH_ID);
CREATE INDEX IX_SPT_LOG_USER ON SPT_QUERY_LOG (USER_ID);
CREATE INDEX IX_SPT_LOG_START ON SPT_QUERY_LOG (START_TIME);
CREATE INDEX IX_SPT_LOG_SEQ ON SPT_QUERY_LOG (SEQ_ID);

CREATE TABLE SPT_TUNING_TRACKER (
    ID                              INTEGER PRIMARY KEY AUTOINCREMENT,
    GROUP_ID                        INTEGER NOT NULL REFERENCES SPT_QUERY_GROUP (ID),
    WORKFLOW_STATUS                 TEXT    NOT NULL DEFAULT 'NEW',
    PRIORITY                        TEXT    NOT NULL DEFAULT 'MEDIUM' CHECK (PRIORITY IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    SAMPLE_QUERY_FORMATTED          TEXT,
    CLEANSED_QUERY                  TEXT,
    OPTIMIZED_QUERY                 TEXT,
    DEV_TEAM_LEAD                   TEXT,
    DEV_TEAM_STATUS                 TEXT,
    CLOUDERA_TEAM_LEAD              TEXT,
    SME_TEAM_LEAD                   TEXT,
    OPTIMIZED_SQL_STATUS            TEXT,
    CLOUDERA_POST_RUN_VALIDATION    TEXT,
    OG_RUN_DURATION_MINUTES         NUMERIC,
    POST_RUN_DURATION_MINUTES       NUMERIC,
    OG_EXECUTION_TIME_SECONDS       NUMERIC,
    POST_RUN_EXECUTION_TIME_SECONDS NUMERIC,
    OG_TEARDOWN_TIME_SECONDS        NUMERIC,
    POST_RUN_TEARDOWN_TIME_SECONDS  NUMERIC,
    OG_TEARDOWN_PCT                 NUMERIC,
    POST_RUN_TEARDOWN_PCT           NUMERIC,
    THEME                           TEXT,
    SME_VALIDATION                  TEXT,
    INSTALL_STATUS                  TEXT,
    EXECUTE_STATUS                  TEXT,
    VALIDATION_STATUS               TEXT,
    CHANGES                         TEXT,
    PROBLEM                         TEXT,
    RECOMMENDATIONS                 TEXT,
    CREATED_AT                      TIMESTAMP NOT NULL,
    CREATED_BY                      TEXT,
    UPDATED_AT                      TIMESTAMP,
    UPDATED_BY                      TEXT,
    VERSION                         INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT UK_SPT_TRACKER_GROUP UNIQUE (GROUP_ID)
);
CREATE INDEX IX_SPT_TRACKER_STATUS ON SPT_TUNING_TRACKER (WORKFLOW_STATUS);

CREATE TABLE SPT_PROMPT_TEMPLATE (
    ID            INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME          TEXT    NOT NULL,
    SQL_ENGINE    TEXT    NOT NULL,
    VERSION_NO    INTEGER NOT NULL,
    TEMPLATE_TEXT TEXT    NOT NULL,
    ACTIVE        INTEGER NOT NULL DEFAULT 1 CHECK (ACTIVE IN (0, 1)),
    NOTES         TEXT,
    CREATED_AT    TIMESTAMP NOT NULL,
    CREATED_BY    TEXT,
    CONSTRAINT UK_SPT_PROMPT_VER UNIQUE (NAME, VERSION_NO)
);

CREATE TABLE SPT_OPTIMIZATION_RUN (
    ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
    GROUP_ID            INTEGER NOT NULL REFERENCES SPT_QUERY_GROUP (ID),
    PROMPT_TEMPLATE_ID  INTEGER REFERENCES SPT_PROMPT_TEMPLATE (ID),
    MODEL_NAME          TEXT,
    PROMPT_TEXT         TEXT,
    RESPONSE_RAW        TEXT,
    CHANGE_NARRATIVE    TEXT,
    OPTIMIZED_SQL       TEXT,
    STATUS              TEXT    NOT NULL CHECK (STATUS IN ('PENDING', 'COMPLETED', 'FAILED')),
    OUTCOME             TEXT CHECK (OUTCOME IS NULL OR OUTCOME IN ('ACCEPTED', 'REJECTED')),
    ERROR_MESSAGE       TEXT,
    REQUESTED_AT        TIMESTAMP NOT NULL,
    COMPLETED_AT        TIMESTAMP,
    REQUESTED_BY        TEXT
);
CREATE INDEX IX_SPT_OPT_GROUP ON SPT_OPTIMIZATION_RUN (GROUP_ID);

CREATE TABLE SPT_SQL_DIAGNOSTIC (
    ID                    INTEGER PRIMARY KEY AUTOINCREMENT,
    GROUP_ID              INTEGER NOT NULL REFERENCES SPT_QUERY_GROUP (ID),
    PHASE                 TEXT    NOT NULL CHECK (PHASE IN ('ORIGINAL', 'OPTIMIZED')),
    OPTIMIZATION_RUN_ID   INTEGER REFERENCES SPT_OPTIMIZATION_RUN (ID),
    QUERY_ID              TEXT,
    SQL_TEXT              TEXT,
    ROW_COUNT             INTEGER,
    RUN_DURATION_SECONDS  NUMERIC,
    EXPLAIN_PLAN          TEXT,
    PROFILE_RAW           TEXT,
    PROFILE_SUMMARY       TEXT,
    EXEC_SUMMARY          TEXT,
    STATUS                TEXT    NOT NULL CHECK (STATUS IN ('CAPTURED', 'FAILED', 'TIMEOUT')),
    ERROR_MESSAGE         TEXT,
    CAPTURED_AT           TIMESTAMP NOT NULL,
    CAPTURED_BY           TEXT
);
CREATE INDEX IX_SPT_DIAG_GROUP ON SPT_SQL_DIAGNOSTIC (GROUP_ID, PHASE);

CREATE TABLE SPT_TABLE_DDL (
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    GROUP_ID    INTEGER NOT NULL REFERENCES SPT_QUERY_GROUP (ID),
    TABLE_NAME  TEXT    NOT NULL,
    DDL_TEXT    TEXT,
    ROW_COUNT   INTEGER,
    CAPTURED_AT TIMESTAMP NOT NULL,
    CAPTURED_BY TEXT
);
CREATE INDEX IX_SPT_DDL_GROUP ON SPT_TABLE_DDL (GROUP_ID);

CREATE TABLE SPT_FEEDBACK (
    ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
    GROUP_ID            INTEGER NOT NULL REFERENCES SPT_QUERY_GROUP (ID),
    OPTIMIZATION_RUN_ID INTEGER REFERENCES SPT_OPTIMIZATION_RUN (ID),
    SOURCE_ROLE         TEXT    NOT NULL CHECK (SOURCE_ROLE IN ('BUSINESS_USER', 'CLIENT_DEV', 'CLOUDERA', 'SME')),
    DECISION            TEXT    NOT NULL CHECK (DECISION IN ('ADOPTED', 'REJECTED', 'COMMENT')),
    COMMENTS            TEXT,
    CREATED_AT          TIMESTAMP NOT NULL,
    CREATED_BY          TEXT
);
CREATE INDEX IX_SPT_FB_GROUP ON SPT_FEEDBACK (GROUP_ID);

CREATE TABLE SPT_CUSTOM_FIELD (
    ID            INTEGER PRIMARY KEY AUTOINCREMENT,
    ENTITY_TYPE   TEXT    NOT NULL CHECK (ENTITY_TYPE IN ('TRACKER', 'GROUP', 'LOG')),
    FIELD_KEY     TEXT    NOT NULL,
    LABEL         TEXT    NOT NULL,
    DATA_TYPE     TEXT    NOT NULL CHECK (DATA_TYPE IN ('TEXT', 'LONG_TEXT', 'NUMBER', 'DATE', 'BOOLEAN', 'ENUM')),
    OPTIONS_CSV   TEXT,
    DISPLAY_ORDER INTEGER NOT NULL DEFAULT 0,
    REQUIRED      INTEGER NOT NULL DEFAULT 0,
    ACTIVE        INTEGER NOT NULL DEFAULT 1,
    CREATED_AT    TIMESTAMP NOT NULL,
    CREATED_BY    TEXT,
    CONSTRAINT UK_SPT_CF_KEY UNIQUE (ENTITY_TYPE, FIELD_KEY)
);

CREATE TABLE SPT_CUSTOM_FIELD_VALUE (
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    FIELD_ID    INTEGER NOT NULL REFERENCES SPT_CUSTOM_FIELD (ID) ON DELETE CASCADE,
    ENTITY_ID   INTEGER NOT NULL,
    VALUE_TEXT  TEXT,
    UPDATED_AT  TIMESTAMP NOT NULL,
    UPDATED_BY  TEXT,
    CONSTRAINT UK_SPT_CFV UNIQUE (FIELD_ID, ENTITY_ID)
);
CREATE INDEX IX_SPT_CFV_ENTITY ON SPT_CUSTOM_FIELD_VALUE (ENTITY_ID);

CREATE TABLE SPT_AUDIT_EVENT (
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    ENTITY_TYPE TEXT    NOT NULL,
    ENTITY_ID   INTEGER NOT NULL,
    ACTION      TEXT    NOT NULL,
    FIELD_NAME  TEXT,
    OLD_VALUE   TEXT,
    NEW_VALUE   TEXT,
    CHANGED_AT  TIMESTAMP NOT NULL,
    CHANGED_BY  TEXT
);
CREATE INDEX IX_SPT_AUDIT_ENTITY ON SPT_AUDIT_EVENT (ENTITY_TYPE, ENTITY_ID);

CREATE VIEW SPT_TRACKER_V AS
SELECT t.ID                         AS TRACKER_ID,
       g.ID                         AS GROUP_ID,
       g.GROUP_SIZE,
       g.DISTINCT_USERS,
       g.FINGERPRINT,
       g.AVG_DURATION_MINUTES,
       g.MIN_DURATION_MINUTES,
       g.MAX_DURATION_MINUTES,
       g.TOTAL_DURATION_MINUTES,
       g.SAMPLE_QUERY_SEQ_ID,
       g.SAMPLE_QUERY               AS SAMPLE_QUERY_RAW,
       t.SAMPLE_QUERY_FORMATTED,
       g.ROW_INDICES,
       t.CLEANSED_QUERY,
       t.OPTIMIZED_QUERY,
       t.DEV_TEAM_LEAD,
       t.DEV_TEAM_STATUS,
       t.CLOUDERA_TEAM_LEAD,
       t.SME_TEAM_LEAD,
       t.OPTIMIZED_SQL_STATUS,
       t.CLOUDERA_POST_RUN_VALIDATION,
       t.OG_RUN_DURATION_MINUTES,
       t.POST_RUN_DURATION_MINUTES,
       t.OG_EXECUTION_TIME_SECONDS,
       t.POST_RUN_EXECUTION_TIME_SECONDS,
       t.OG_TEARDOWN_TIME_SECONDS,
       t.POST_RUN_TEARDOWN_TIME_SECONDS,
       t.OG_TEARDOWN_PCT,
       t.POST_RUN_TEARDOWN_PCT,
       t.THEME,
       t.SME_VALIDATION,
       t.INSTALL_STATUS,
       t.EXECUTE_STATUS,
       t.VALIDATION_STATUS,
       t.CHANGES,
       t.PROBLEM,
       t.RECOMMENDATIONS,
       t.WORKFLOW_STATUS,
       t.PRIORITY,
       t.UPDATED_AT,
       t.UPDATED_BY
  FROM SPT_TUNING_TRACKER t
  JOIN SPT_QUERY_GROUP g ON g.ID = t.GROUP_ID;
