-- SQLite twin of oracle/V3__load_deduplication.sql (see that file for the design notes).

ALTER TABLE SPT_QUERY_LOG ADD COLUMN ROW_KEY TEXT;
ALTER TABLE SPT_QUERY_LOG ADD COLUMN SEEN_COUNT INTEGER NOT NULL DEFAULT 1;
ALTER TABLE SPT_QUERY_LOG ADD COLUMN LAST_SEEN_AT TIMESTAMP;
ALTER TABLE SPT_QUERY_LOG ADD COLUMN LAST_SEEN_BATCH_ID INTEGER;
CREATE UNIQUE INDEX UX_SPT_LOG_ROW_KEY ON SPT_QUERY_LOG (ROW_KEY);

CREATE TABLE SPT_SOURCE_FILE (
    ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
    CONTENT_HASH        TEXT    NOT NULL,
    FILE_NAME           TEXT,
    FILE_SIZE           INTEGER,
    LOAD_COUNT          INTEGER NOT NULL DEFAULT 1,
    PROCESSED_BATCH_ID  INTEGER NOT NULL REFERENCES SPT_INGESTION_BATCH (ID),
    LAST_BATCH_ID       INTEGER NOT NULL REFERENCES SPT_INGESTION_BATCH (ID),
    FIRST_LOADED_AT     TIMESTAMP NOT NULL,
    LAST_LOADED_AT      TIMESTAMP NOT NULL,
    CONSTRAINT UK_SPT_SOURCE_FILE_HASH UNIQUE (CONTENT_HASH)
);

ALTER TABLE SPT_INGESTION_BATCH ADD COLUMN ROWS_DUPLICATE INTEGER NOT NULL DEFAULT 0;
ALTER TABLE SPT_INGESTION_BATCH ADD COLUMN CONTENT_HASH TEXT;
ALTER TABLE SPT_INGESTION_BATCH ADD COLUMN SOURCE_FILE_ID INTEGER REFERENCES SPT_SOURCE_FILE (ID);
ALTER TABLE SPT_INGESTION_BATCH ADD COLUMN FILE_LOAD_NUMBER INTEGER;
ALTER TABLE SPT_INGESTION_BATCH ADD COLUMN DUPLICATE_OF_BATCH_ID INTEGER REFERENCES SPT_INGESTION_BATCH (ID);

CREATE TABLE SPT_QUERY_LOG_SIGHTING (
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    LOG_ID      INTEGER NOT NULL REFERENCES SPT_QUERY_LOG (ID),
    BATCH_ID    INTEGER NOT NULL REFERENCES SPT_INGESTION_BATCH (ID),
    SEEN_AT     TIMESTAMP NOT NULL,
    IS_FIRST    INTEGER NOT NULL DEFAULT 0 CHECK (IS_FIRST IN (0, 1)),
    CONSTRAINT UK_SPT_SIGHTING UNIQUE (LOG_ID, BATCH_ID)
);
CREATE INDEX IX_SPT_SIGHT_BATCH ON SPT_QUERY_LOG_SIGHTING (BATCH_ID);

INSERT INTO SPT_QUERY_LOG_SIGHTING (LOG_ID, BATCH_ID, SEEN_AT, IS_FIRST)
SELECT ID, BATCH_ID, CREATED_AT, 1 FROM SPT_QUERY_LOG;
UPDATE SPT_QUERY_LOG SET LAST_SEEN_AT = CREATED_AT, LAST_SEEN_BATCH_ID = BATCH_ID;
