-- =====================================================================
-- V4 (SQLite twin of oracle/V4): analytics & tuning iterations
--   SPT_LOOKUP               admin-editable dropdown values (themes, statuses, reasons, ...)
--   SPT_TUNING_ITERATION     every tuning attempt of a tracker item with its test metrics;
--                            the best one is selected, then adopted (or rejected)
--   SPT_USER_DIRECTORY       user -> user group / department (bad queries by user group)
--   SPT_TUNING_TRACKER       request source (log / proactive UAT / user request), stage
--                            timestamps for turnaround, CPU / rows / tables metrics
--   SPT_SQL_DIAGNOSTIC       iteration link + parsed CPU / rows / tables metrics
--   SPT_FEEDBACK             iteration link + rejection reason
-- =====================================================================

CREATE TABLE SPT_LOOKUP (
    ID            INTEGER PRIMARY KEY AUTOINCREMENT,
    CATEGORY      TEXT    NOT NULL,
    LOOKUP_VALUE  TEXT    NOT NULL,
    SORT_ORDER    INTEGER NOT NULL DEFAULT 0,
    TONE          TEXT,
    ACTIVE        INTEGER NOT NULL DEFAULT 1 CHECK (ACTIVE IN (0, 1)),
    CREATED_AT    TIMESTAMP NOT NULL,
    CONSTRAINT UK_SPT_LOOKUP UNIQUE (CATEGORY, LOOKUP_VALUE)
);

CREATE TABLE SPT_TUNING_ITERATION (
    ID                      INTEGER PRIMARY KEY AUTOINCREMENT,
    TRACKER_ID              INTEGER NOT NULL REFERENCES SPT_TUNING_TRACKER (ID),
    ITERATION_NO            INTEGER NOT NULL,
    SOURCE                  TEXT    NOT NULL CHECK (SOURCE IN ('AI_AGENT', 'MANUAL')),
    OPTIMIZATION_RUN_ID     INTEGER REFERENCES SPT_OPTIMIZATION_RUN (ID),
    OPTIMIZED_SQL           TEXT,
    CHANGE_NARRATIVE        TEXT,
    STATUS                  TEXT    NOT NULL CHECK (STATUS IN ('PROPOSED', 'TESTED', 'FAILED', 'SELECTED', 'ADOPTED', 'REJECTED')),
    RUN_DURATION_MINUTES    NUMERIC,
    EXECUTION_TIME_SECONDS  NUMERIC,
    TEARDOWN_TIME_SECONDS   NUMERIC,
    CPU_SECONDS             NUMERIC,
    ROWS_SCANNED            INTEGER,
    BYTES_SCANNED           INTEGER,
    TABLES_SCANNED          INTEGER,
    PEAK_MEMORY_MB          NUMERIC,
    RESULT_ROW_COUNT        INTEGER,
    RESULT_MATCHES          INTEGER CHECK (RESULT_MATCHES IS NULL OR RESULT_MATCHES IN (0, 1)),
    NOTES                   TEXT,
    TESTED_AT               TIMESTAMP,
    TESTED_BY               TEXT,
    CREATED_AT              TIMESTAMP NOT NULL,
    CREATED_BY              TEXT,
    UPDATED_AT              TIMESTAMP,
    VERSION                 INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT UK_SPT_ITERATION_NO UNIQUE (TRACKER_ID, ITERATION_NO)
);
CREATE INDEX IX_SPT_ITER_TRACKER ON SPT_TUNING_ITERATION (TRACKER_ID);

ALTER TABLE SPT_TUNING_TRACKER ADD COLUMN REQUEST_SOURCE TEXT NOT NULL DEFAULT 'LOG_DETECTED' CHECK (REQUEST_SOURCE IN ('LOG_DETECTED', 'PROACTIVE_UAT', 'USER_REQUEST'));
ALTER TABLE SPT_TUNING_TRACKER ADD COLUMN REQUESTED_BY TEXT;
ALTER TABLE SPT_TUNING_TRACKER ADD COLUMN ENVIRONMENT TEXT;
ALTER TABLE SPT_TUNING_TRACKER ADD COLUMN STAGE_CHANGED_AT TIMESTAMP;
ALTER TABLE SPT_TUNING_TRACKER ADD COLUMN ADOPTED_AT TIMESTAMP;
ALTER TABLE SPT_TUNING_TRACKER ADD COLUMN CLOSED_AT TIMESTAMP;
ALTER TABLE SPT_TUNING_TRACKER ADD COLUMN SELECTED_ITERATION_ID INTEGER;
ALTER TABLE SPT_TUNING_TRACKER ADD COLUMN OG_CPU_SECONDS NUMERIC;
ALTER TABLE SPT_TUNING_TRACKER ADD COLUMN POST_RUN_CPU_SECONDS NUMERIC;
ALTER TABLE SPT_TUNING_TRACKER ADD COLUMN OG_ROWS_SCANNED INTEGER;
ALTER TABLE SPT_TUNING_TRACKER ADD COLUMN POST_RUN_ROWS_SCANNED INTEGER;
ALTER TABLE SPT_TUNING_TRACKER ADD COLUMN OG_TABLES_SCANNED INTEGER;
ALTER TABLE SPT_TUNING_TRACKER ADD COLUMN POST_RUN_TABLES_SCANNED INTEGER;
ALTER TABLE SPT_TUNING_TRACKER ADD COLUMN OG_BYTES_SCANNED INTEGER;
ALTER TABLE SPT_TUNING_TRACKER ADD COLUMN POST_RUN_BYTES_SCANNED INTEGER;
ALTER TABLE SPT_TUNING_TRACKER ADD COLUMN OG_PEAK_MEMORY_MB NUMERIC;
ALTER TABLE SPT_TUNING_TRACKER ADD COLUMN POST_RUN_PEAK_MEMORY_MB NUMERIC;
UPDATE SPT_TUNING_TRACKER SET STAGE_CHANGED_AT = COALESCE(UPDATED_AT, CREATED_AT);
UPDATE SPT_TUNING_TRACKER SET ADOPTED_AT = COALESCE(UPDATED_AT, CREATED_AT), CLOSED_AT = COALESCE(UPDATED_AT, CREATED_AT)
 WHERE WORKFLOW_STATUS = 'ADOPTED';
UPDATE SPT_TUNING_TRACKER SET CLOSED_AT = COALESCE(UPDATED_AT, CREATED_AT) WHERE WORKFLOW_STATUS = 'REJECTED';
CREATE INDEX IX_SPT_TRACKER_ADOPTED ON SPT_TUNING_TRACKER (ADOPTED_AT);
CREATE INDEX IX_SPT_TRACKER_THEME ON SPT_TUNING_TRACKER (THEME);
CREATE INDEX IX_SPT_GROUP_FIRST_SEEN ON SPT_QUERY_GROUP (FIRST_SEEN);

ALTER TABLE SPT_SQL_DIAGNOSTIC ADD COLUMN ITERATION_ID INTEGER REFERENCES SPT_TUNING_ITERATION (ID);
ALTER TABLE SPT_SQL_DIAGNOSTIC ADD COLUMN EXECUTION_TIME_SECONDS NUMERIC;
ALTER TABLE SPT_SQL_DIAGNOSTIC ADD COLUMN TEARDOWN_TIME_SECONDS NUMERIC;
ALTER TABLE SPT_SQL_DIAGNOSTIC ADD COLUMN CPU_SECONDS NUMERIC;
ALTER TABLE SPT_SQL_DIAGNOSTIC ADD COLUMN ROWS_SCANNED INTEGER;
ALTER TABLE SPT_SQL_DIAGNOSTIC ADD COLUMN BYTES_SCANNED INTEGER;
ALTER TABLE SPT_SQL_DIAGNOSTIC ADD COLUMN TABLES_SCANNED INTEGER;
ALTER TABLE SPT_SQL_DIAGNOSTIC ADD COLUMN PEAK_MEMORY_MB NUMERIC;

ALTER TABLE SPT_FEEDBACK ADD COLUMN ITERATION_ID INTEGER REFERENCES SPT_TUNING_ITERATION (ID);
ALTER TABLE SPT_FEEDBACK ADD COLUMN REJECTION_REASON TEXT;

CREATE TABLE SPT_USER_DIRECTORY (
    USER_ID       TEXT PRIMARY KEY,
    DISPLAY_NAME  TEXT,
    USER_GROUP    TEXT,
    DEPARTMENT    TEXT,
    ACTIVE        INTEGER NOT NULL DEFAULT 1 CHECK (ACTIVE IN (0, 1)),
    UPDATED_AT    TIMESTAMP NOT NULL,
    UPDATED_BY    TEXT
);
CREATE INDEX IX_SPT_USERDIR_GROUP ON SPT_USER_DIRECTORY (USER_GROUP);

DROP VIEW SPT_TRACKER_V;
CREATE VIEW SPT_TRACKER_V AS
SELECT t.ID                         AS TRACKER_ID,
       g.ID                         AS GROUP_ID,
       g.GROUP_SIZE,
       g.DISTINCT_USERS,
       g.FINGERPRINT,
       g.AVG_DURATION_MINUTES,
       g.MIN_DURATION_MINUTES,
       g.MAX_DURATION_MINUTES,
       g.TOTAL_DURATION_MINUTES,
       g.FIRST_SEEN,
       g.LAST_SEEN,
       g.SAMPLE_QUERY_SEQ_ID,
       g.SAMPLE_QUERY               AS SAMPLE_QUERY_RAW,
       t.SAMPLE_QUERY_FORMATTED,
       g.ROW_INDICES,
       t.CLEANSED_QUERY,
       t.OPTIMIZED_QUERY,
       t.DEV_TEAM_LEAD,
       t.DEV_TEAM_STATUS,
       t.CLOUDERA_TEAM_LEAD,
       t.SME_TEAM_LEAD,
       t.OPTIMIZED_SQL_STATUS,
       t.CLOUDERA_POST_RUN_VALIDATION,
       t.OG_RUN_DURATION_MINUTES,
       t.POST_RUN_DURATION_MINUTES,
       t.OG_EXECUTION_TIME_SECONDS,
       t.POST_RUN_EXECUTION_TIME_SECONDS,
       t.OG_TEARDOWN_TIME_SECONDS,
       t.POST_RUN_TEARDOWN_TIME_SECONDS,
       t.OG_TEARDOWN_PCT,
       t.POST_RUN_TEARDOWN_PCT,
       t.OG_CPU_SECONDS,
       t.POST_RUN_CPU_SECONDS,
       t.OG_ROWS_SCANNED,
       t.POST_RUN_ROWS_SCANNED,
       t.OG_TABLES_SCANNED,
       t.POST_RUN_TABLES_SCANNED,
       t.THEME,
       t.SME_VALIDATION,
       t.INSTALL_STATUS,
       t.EXECUTE_STATUS,
       t.VALIDATION_STATUS,
       t.CHANGES,
       t.PROBLEM,
       t.RECOMMENDATIONS,
       t.WORKFLOW_STATUS,
       t.PRIORITY,
       t.REQUEST_SOURCE,
       t.REQUESTED_BY,
       t.ENVIRONMENT,
       t.SELECTED_ITERATION_ID,
       t.CREATED_AT,
       t.STAGE_CHANGED_AT,
       t.ADOPTED_AT,
       t.CLOSED_AT,
       t.UPDATED_AT,
       t.UPDATED_BY
  FROM SPT_TUNING_TRACKER t
  JOIN SPT_QUERY_GROUP g ON g.ID = t.GROUP_ID;

-- default dropdown values (edit in Administration -> Dropdown values)
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('THEME', 'Partition pruning', 10, 'info', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('THEME', 'Trade all', 20, 'info', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('THEME', 'Teardown', 30, 'info', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('THEME', 'Join strategy', 40, 'info', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('THEME', 'Missing statistics', 50, 'info', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('THEME', 'Data skew', 60, 'info', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('THEME', 'Wide scans / SELECT *', 70, 'info', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('THEME', 'Spill to disk', 80, 'info', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('THEME', 'Small files', 90, 'info', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('THEME', 'Complex views', 100, 'info', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('THEME', 'Other', 110, 'muted', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('DEV_TEAM_STATUS', 'Not started', 10, 'muted', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('DEV_TEAM_STATUS', 'In analysis', 20, 'info', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('DEV_TEAM_STATUS', 'In progress', 30, 'info', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('DEV_TEAM_STATUS', 'In review', 40, 'warn', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('DEV_TEAM_STATUS', 'Blocked', 50, 'bad', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('DEV_TEAM_STATUS', 'Done', 60, 'ok', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('OPTIMIZED_SQL_STATUS', 'Not started', 10, 'muted', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('OPTIMIZED_SQL_STATUS', 'In progress', 20, 'info', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('OPTIMIZED_SQL_STATUS', 'Candidate ready', 30, 'warn', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('OPTIMIZED_SQL_STATUS', 'Validated', 40, 'ok', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('OPTIMIZED_SQL_STATUS', 'Not possible', 50, 'bad', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('CLOUDERA_POST_RUN_VALIDATION', 'Pending', 10, 'muted', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('CLOUDERA_POST_RUN_VALIDATION', 'Passed', 20, 'ok', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('CLOUDERA_POST_RUN_VALIDATION', 'Failed', 30, 'bad', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('CLOUDERA_POST_RUN_VALIDATION', 'Not required', 40, 'muted', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('SME_VALIDATION', 'Pending', 10, 'muted', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('SME_VALIDATION', 'Approved', 20, 'ok', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('SME_VALIDATION', 'Rejected', 30, 'bad', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('SME_VALIDATION', 'Not required', 40, 'muted', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('INSTALL_STATUS', 'Pending', 10, 'muted', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('INSTALL_STATUS', 'Scheduled', 20, 'info', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('INSTALL_STATUS', 'Installed', 30, 'ok', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('INSTALL_STATUS', 'Rolled back', 40, 'bad', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('INSTALL_STATUS', 'Not applicable', 50, 'muted', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('EXECUTE_STATUS', 'Pending', 10, 'muted', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('EXECUTE_STATUS', 'Running', 20, 'info', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('EXECUTE_STATUS', 'Succeeded', 30, 'ok', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('EXECUTE_STATUS', 'Failed', 40, 'bad', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('EXECUTE_STATUS', 'Not applicable', 50, 'muted', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('VALIDATION_STATUS', 'Pending', 10, 'muted', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('VALIDATION_STATUS', 'Passed', 20, 'ok', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('VALIDATION_STATUS', 'Failed', 30, 'bad', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('VALIDATION_STATUS', 'Not applicable', 40, 'muted', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('ENVIRONMENT', 'PROD', 10, 'info', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('ENVIRONMENT', 'UAT', 20, 'info', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('ENVIRONMENT', 'DEV', 30, 'info', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('REJECTION_REASON', 'Inaccurate results', 10, 'bad', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('REJECTION_REASON', 'No performance gain', 20, 'warn', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('REJECTION_REASON', 'Business logic changed', 30, 'warn', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('REJECTION_REASON', 'Not feasible to deploy', 40, 'warn', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT) VALUES ('REJECTION_REASON', 'Other', 50, 'muted', 1, strftime('%Y-%m-%d %H:%M:%f', 'now'));
