-- =====================================================================
-- Load de-duplication: every log row is processed (inserted, fingerprinted,
-- grouped) exactly once. Re-loads only record a sighting.
--
--   SPT_QUERY_LOG.ROW_KEY        identity hash of the row (unique)
--   SPT_QUERY_LOG.SEEN_COUNT     number of loads the row appeared in
--   SPT_QUERY_LOG_SIGHTING       one row per (log row, load) - load history
--   SPT_SOURCE_FILE              one row per distinct file content (SHA-256)
--                                with how many times it was loaded
--   SPT_INGESTION_BATCH          new / duplicate counters, file reference and
--                                DUPLICATE_OF_BATCH_ID when the whole file was
--                                already loaded (not re-parsed)
-- =====================================================================

ALTER TABLE SPT_QUERY_LOG ADD (
    ROW_KEY             VARCHAR2(64),
    SEEN_COUNT          NUMBER(10)  DEFAULT 1 NOT NULL,
    LAST_SEEN_AT        TIMESTAMP,
    LAST_SEEN_BATCH_ID  NUMBER(19)
);
COMMENT ON COLUMN SPT_QUERY_LOG.ROW_KEY IS 'SHA-256 identity of the log row (see spt.ingestion.row-identity). Rows with an existing key are never re-processed.';
CREATE UNIQUE INDEX UX_SPT_LOG_ROW_KEY ON SPT_QUERY_LOG (ROW_KEY);

CREATE TABLE SPT_SOURCE_FILE (
    ID                  NUMBER(19)      GENERATED BY DEFAULT AS IDENTITY,
    CONTENT_HASH        VARCHAR2(64)    NOT NULL,
    FILE_NAME           VARCHAR2(500),
    FILE_SIZE           NUMBER(19),
    LOAD_COUNT          NUMBER(10)      DEFAULT 1 NOT NULL,
    PROCESSED_BATCH_ID  NUMBER(19)      NOT NULL,
    LAST_BATCH_ID       NUMBER(19)      NOT NULL,
    FIRST_LOADED_AT     TIMESTAMP       NOT NULL,
    LAST_LOADED_AT      TIMESTAMP       NOT NULL,
    CONSTRAINT PK_SPT_SOURCE_FILE PRIMARY KEY (ID),
    CONSTRAINT UK_SPT_SOURCE_FILE_HASH UNIQUE (CONTENT_HASH),
    CONSTRAINT FK_SPT_SF_PROCESSED FOREIGN KEY (PROCESSED_BATCH_ID) REFERENCES SPT_INGESTION_BATCH (ID),
    CONSTRAINT FK_SPT_SF_LAST FOREIGN KEY (LAST_BATCH_ID) REFERENCES SPT_INGESTION_BATCH (ID)
);
COMMENT ON COLUMN SPT_SOURCE_FILE.PROCESSED_BATCH_ID IS 'The import that actually parsed this file; later identical uploads reuse its rows.';

ALTER TABLE SPT_INGESTION_BATCH ADD (
    ROWS_DUPLICATE          NUMBER(10)      DEFAULT 0 NOT NULL,
    CONTENT_HASH            VARCHAR2(64),
    SOURCE_FILE_ID          NUMBER(19),
    FILE_LOAD_NUMBER        NUMBER(10),
    DUPLICATE_OF_BATCH_ID   NUMBER(19)
);
ALTER TABLE SPT_INGESTION_BATCH ADD CONSTRAINT FK_SPT_BATCH_FILE
    FOREIGN KEY (SOURCE_FILE_ID) REFERENCES SPT_SOURCE_FILE (ID);
ALTER TABLE SPT_INGESTION_BATCH ADD CONSTRAINT FK_SPT_BATCH_DUP
    FOREIGN KEY (DUPLICATE_OF_BATCH_ID) REFERENCES SPT_INGESTION_BATCH (ID);
COMMENT ON COLUMN SPT_INGESTION_BATCH.ROWS_LOADED IS 'New rows inserted and processed by this import.';
COMMENT ON COLUMN SPT_INGESTION_BATCH.ROWS_DUPLICATE IS 'Rows already loaded earlier (or repeated in the same file); recorded as sightings only.';
COMMENT ON COLUMN SPT_INGESTION_BATCH.FILE_LOAD_NUMBER IS 'Nth time this exact file content was loaded (1 = first).';

CREATE TABLE SPT_QUERY_LOG_SIGHTING (
    ID          NUMBER(19)  GENERATED BY DEFAULT AS IDENTITY,
    LOG_ID      NUMBER(19)  NOT NULL,
    BATCH_ID    NUMBER(19)  NOT NULL,
    SEEN_AT     TIMESTAMP   NOT NULL,
    IS_FIRST    NUMBER(1)   DEFAULT 0 NOT NULL,
    CONSTRAINT PK_SPT_QUERY_LOG_SIGHTING PRIMARY KEY (ID),
    CONSTRAINT UK_SPT_SIGHTING UNIQUE (LOG_ID, BATCH_ID),
    CONSTRAINT FK_SPT_SIGHT_LOG FOREIGN KEY (LOG_ID) REFERENCES SPT_QUERY_LOG (ID),
    CONSTRAINT FK_SPT_SIGHT_BATCH FOREIGN KEY (BATCH_ID) REFERENCES SPT_INGESTION_BATCH (ID),
    CONSTRAINT CK_SPT_SIGHT_FIRST CHECK (IS_FIRST IN (0, 1))
);
CREATE INDEX IX_SPT_SIGHT_BATCH ON SPT_QUERY_LOG_SIGHTING (BATCH_ID);

-- existing rows: their original load is their first sighting (ROW_KEY is back-filled by the service on start-up)
INSERT INTO SPT_QUERY_LOG_SIGHTING (LOG_ID, BATCH_ID, SEEN_AT, IS_FIRST)
SELECT ID, BATCH_ID, CREATED_AT, 1 FROM SPT_QUERY_LOG;
UPDATE SPT_QUERY_LOG SET LAST_SEEN_AT = CREATED_AT, LAST_SEEN_BATCH_ID = BATCH_ID;
