-- =====================================================================
-- V5: pooled IDs for the high-volume tables
--
-- IDENTITY columns force one INSERT round trip per row (the database hands out each id), so a 2000-row
-- import cost thousands of round trips. These sequences hand out blocks of 1000 ids (Hibernate
-- "pooled-lo" optimizer): the service numbers rows itself and sends the INSERTs as JDBC batches.
-- The ID columns stay GENERATED BY DEFAULT AS IDENTITY, which accepts the ids supplied by the service.
-- =====================================================================
DECLARE
    PROCEDURE make_sequence(p_sequence VARCHAR2, p_table VARCHAR2) IS
        v_start NUMBER;
    BEGIN
        EXECUTE IMMEDIATE 'SELECT NVL(MAX(ID), 0) + 1 FROM ' || p_table INTO v_start;
        EXECUTE IMMEDIATE 'CREATE SEQUENCE ' || p_sequence || ' START WITH ' || v_start
            || ' INCREMENT BY 1000 NOCYCLE';
    END;
BEGIN
    make_sequence('SPT_QUERY_LOG_SEQ', 'SPT_QUERY_LOG');
    make_sequence('SPT_QUERY_LOG_SIGHTING_SEQ', 'SPT_QUERY_LOG_SIGHTING');
    make_sequence('SPT_QUERY_GROUP_SEQ', 'SPT_QUERY_GROUP');
END;
/
