-- =====================================================================
-- SQL Performance & Tuning (SPT) - ORACLE (19c+)
-- DROP and RE-CREATE every table and view, then load the initial values.
--
-- !!! DESTRUCTIVE: all SPT data (logs, groups, tracker, history) is lost. !!!
--
-- Equivalent to Flyway migrations V1-V4 (backend/src/main/resources/db/migration/oracle)
-- in a single script, for DBAs who build or reset an environment by hand.
--
-- Run as the schema owner (e.g. SPT_OWNER, see 00_create_schema.sql) with SQL*Plus, SQLcl or
-- SQL Developer ("Run Script", F5):
--     sqlplus SPT_OWNER@//host:1521/SERVICE @01_drop_and_create_schema.sql
--
-- Flyway: the script also drops "flyway_schema_history". Start the service once with
--     SPRING_FLYWAY_BASELINE_ON_MIGRATE=true  SPRING_FLYWAY_BASELINE_VERSION=4
-- so Flyway records this schema as version 4 and only applies newer migrations (V5+).
-- (Or set spring.flyway.enabled=false and keep the schema up to date with scripts.)
--
-- Contents
--   1. Drop view and tables (missing objects are skipped)
--   2. Tables, constraints, indexes, comments (in dependency order)
--   3. Reporting view SPT_TRACKER_V
--   4. Initial values: AI prompt template, dropdown values (SPT_LOOKUP)
-- =====================================================================

SET DEFINE OFF
SET SQLBLANKLINES ON
SET SQLPREFIX '~'
SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

-- =====================================================================
-- 1. DROP
-- =====================================================================
BEGIN
    BEGIN
        EXECUTE IMMEDIATE 'DROP VIEW SPT_TRACKER_V';
        DBMS_OUTPUT.PUT_LINE('dropped view SPT_TRACKER_V');
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -942 THEN RAISE; END IF;
    END;

    -- children first; CASCADE CONSTRAINTS also removes the circular tracker <-> iteration keys
    FOR t IN (
        SELECT COLUMN_VALUE AS NAME
          FROM TABLE(SYS.ODCIVARCHAR2LIST(
                'SPT_CUSTOM_FIELD_VALUE', 'SPT_CUSTOM_FIELD', 'SPT_AUDIT_EVENT',
                'SPT_FEEDBACK', 'SPT_SQL_DIAGNOSTIC', 'SPT_TABLE_DDL',
                'SPT_TUNING_ITERATION', 'SPT_OPTIMIZATION_RUN', 'SPT_PROMPT_TEMPLATE',
                'SPT_TUNING_TRACKER', 'SPT_QUERY_LOG_SIGHTING', 'SPT_QUERY_LOG',
                'SPT_QUERY_GROUP', 'SPT_SOURCE_FILE', 'SPT_INGESTION_BATCH', 'SPT_DATA_SOURCE',
                'SPT_LOOKUP', 'SPT_USER_DIRECTORY', 'flyway_schema_history'))
    ) LOOP
        BEGIN
            EXECUTE IMMEDIATE 'DROP TABLE "' || t.NAME || '" CASCADE CONSTRAINTS PURGE';
            DBMS_OUTPUT.PUT_LINE('dropped table ' || t.NAME);
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -942 THEN RAISE; END IF;
        END;
    END LOOP;
END;
/

-- =====================================================================
-- 2. TABLES
-- =====================================================================

-- ---------------------------------------------------------------------
-- Source connections used to pull query logs (Oracle / Impala / JDBC)
-- ---------------------------------------------------------------------
CREATE TABLE SPT_DATA_SOURCE (
    ID              NUMBER(19)      GENERATED BY DEFAULT AS IDENTITY,
    NAME            VARCHAR2(100)   NOT NULL,
    SOURCE_TYPE     VARCHAR2(20)    NOT NULL,
    SQL_ENGINE      VARCHAR2(20)    DEFAULT 'IMPALA' NOT NULL,
    JDBC_URL        VARCHAR2(1000)  NOT NULL,
    DRIVER_CLASS    VARCHAR2(200),
    USERNAME        VARCHAR2(200),
    PASSWORD_REF    VARCHAR2(200),
    LOG_QUERY       CLOB            NOT NULL,
    FETCH_SIZE      NUMBER(10)      DEFAULT 1000 NOT NULL,
    LAST_WATERMARK  TIMESTAMP,
    ACTIVE          NUMBER(1)       DEFAULT 1 NOT NULL,
    DESCRIPTION     VARCHAR2(1000),
    CREATED_AT      TIMESTAMP       NOT NULL,
    CREATED_BY      VARCHAR2(100),
    UPDATED_AT      TIMESTAMP,
    UPDATED_BY      VARCHAR2(100),
    VERSION         NUMBER(10)      DEFAULT 0 NOT NULL,
    CONSTRAINT PK_SPT_DATA_SOURCE PRIMARY KEY (ID),
    CONSTRAINT UK_SPT_DATA_SOURCE_NAME UNIQUE (NAME),
    CONSTRAINT CK_SPT_DS_TYPE CHECK (SOURCE_TYPE IN ('ORACLE', 'IMPALA', 'GENERIC_JDBC')),
    CONSTRAINT CK_SPT_DS_ACTIVE CHECK (ACTIVE IN (0, 1))
);
COMMENT ON TABLE SPT_DATA_SOURCE IS 'JDBC sources (Oracle / Impala) the query logs are pulled from.';
COMMENT ON COLUMN SPT_DATA_SOURCE.PASSWORD_REF IS 'Name of an environment variable / Spring property holding the password. Plain-text passwords are never stored.';
COMMENT ON COLUMN SPT_DATA_SOURCE.LOG_QUERY IS 'SELECT returning the standard log columns (SEQ_ID, EXECUTED_QUERY, ...). May reference :since for incremental pulls.';

-- ---------------------------------------------------------------------
-- One row per import (file upload or JDBC pull)
-- ---------------------------------------------------------------------
CREATE TABLE SPT_INGESTION_BATCH (
    ID                      NUMBER(19)      GENERATED BY DEFAULT AS IDENTITY,
    SOURCE_KIND             VARCHAR2(20)    NOT NULL,
    DATA_SOURCE_ID          NUMBER(19),
    SOURCE_NAME             VARCHAR2(500),
    SQL_ENGINE              VARCHAR2(20)    NOT NULL,
    STATUS                  VARCHAR2(30)    NOT NULL,
    ROWS_READ               NUMBER(10)      DEFAULT 0 NOT NULL,
    ROWS_LOADED             NUMBER(10)      DEFAULT 0 NOT NULL,
    ROWS_REJECTED           NUMBER(10)      DEFAULT 0 NOT NULL,
    ROWS_DUPLICATE          NUMBER(10)      DEFAULT 0 NOT NULL,
    GROUPS_AFFECTED         NUMBER(10)      DEFAULT 0 NOT NULL,
    CONTENT_HASH            VARCHAR2(64),
    SOURCE_FILE_ID          NUMBER(19),
    FILE_LOAD_NUMBER        NUMBER(10),
    DUPLICATE_OF_BATCH_ID   NUMBER(19),
    MESSAGE                 VARCHAR2(4000),
    STARTED_AT              TIMESTAMP       NOT NULL,
    COMPLETED_AT            TIMESTAMP,
    CREATED_BY              VARCHAR2(100),
    CONSTRAINT PK_SPT_INGESTION_BATCH PRIMARY KEY (ID),
    CONSTRAINT FK_SPT_BATCH_DS FOREIGN KEY (DATA_SOURCE_ID) REFERENCES SPT_DATA_SOURCE (ID),
    CONSTRAINT FK_SPT_BATCH_DUP FOREIGN KEY (DUPLICATE_OF_BATCH_ID) REFERENCES SPT_INGESTION_BATCH (ID),
    CONSTRAINT CK_SPT_BATCH_KIND CHECK (SOURCE_KIND IN ('CSV', 'EXCEL', 'JDBC')),
    CONSTRAINT CK_SPT_BATCH_STATUS CHECK (STATUS IN ('RUNNING', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'FAILED'))
);
COMMENT ON TABLE SPT_INGESTION_BATCH IS 'One row per import (file upload or JDBC pull) with its counters.';
COMMENT ON COLUMN SPT_INGESTION_BATCH.ROWS_LOADED IS 'New rows inserted and processed by this import.';
COMMENT ON COLUMN SPT_INGESTION_BATCH.ROWS_DUPLICATE IS 'Rows already loaded earlier (or repeated in the same file); recorded as sightings only.';
COMMENT ON COLUMN SPT_INGESTION_BATCH.FILE_LOAD_NUMBER IS 'Nth time this exact file content was loaded (1 = first).';
COMMENT ON COLUMN SPT_INGESTION_BATCH.DUPLICATE_OF_BATCH_ID IS 'Set when the whole file was already loaded: it was not parsed again.';

-- ---------------------------------------------------------------------
-- Distinct uploaded files (SHA-256 of the content) and how often they were loaded
-- ---------------------------------------------------------------------
CREATE TABLE SPT_SOURCE_FILE (
    ID                  NUMBER(19)      GENERATED BY DEFAULT AS IDENTITY,
    CONTENT_HASH        VARCHAR2(64)    NOT NULL,
    FILE_NAME           VARCHAR2(500),
    FILE_SIZE           NUMBER(19),
    LOAD_COUNT          NUMBER(10)      DEFAULT 1 NOT NULL,
    PROCESSED_BATCH_ID  NUMBER(19)      NOT NULL,
    LAST_BATCH_ID       NUMBER(19)      NOT NULL,
    FIRST_LOADED_AT     TIMESTAMP       NOT NULL,
    LAST_LOADED_AT      TIMESTAMP       NOT NULL,
    CONSTRAINT PK_SPT_SOURCE_FILE PRIMARY KEY (ID),
    CONSTRAINT UK_SPT_SOURCE_FILE_HASH UNIQUE (CONTENT_HASH),
    CONSTRAINT FK_SPT_SF_PROCESSED FOREIGN KEY (PROCESSED_BATCH_ID) REFERENCES SPT_INGESTION_BATCH (ID),
    CONSTRAINT FK_SPT_SF_LAST FOREIGN KEY (LAST_BATCH_ID) REFERENCES SPT_INGESTION_BATCH (ID)
);
COMMENT ON TABLE SPT_SOURCE_FILE IS 'Load history per distinct file content; identical uploads are flagged, counted and not re-processed.';
COMMENT ON COLUMN SPT_SOURCE_FILE.PROCESSED_BATCH_ID IS 'The import that actually parsed this file; later identical uploads reuse its rows.';

ALTER TABLE SPT_INGESTION_BATCH ADD CONSTRAINT FK_SPT_BATCH_FILE
    FOREIGN KEY (SOURCE_FILE_ID) REFERENCES SPT_SOURCE_FILE (ID);

-- ---------------------------------------------------------------------
-- Groups of equivalent SQL (same fingerprint = same SQL minus WHERE part)
-- ---------------------------------------------------------------------
CREATE TABLE SPT_QUERY_GROUP (
    ID                      NUMBER(19)      GENERATED BY DEFAULT AS IDENTITY,
    FINGERPRINT             VARCHAR2(64)    NOT NULL,
    SQL_ENGINE              VARCHAR2(20)    NOT NULL,
    GROUP_SIZE              NUMBER(10)      DEFAULT 0 NOT NULL,
    DISTINCT_USERS          NUMBER(10)      DEFAULT 0 NOT NULL,
    USER_IDS                VARCHAR2(4000),
    DURATION_COUNT          NUMBER(10)      DEFAULT 0 NOT NULL,
    AVG_DURATION_MINUTES    NUMBER(14,4),
    MIN_DURATION_MINUTES    NUMBER(14,4),
    MAX_DURATION_MINUTES    NUMBER(14,4),
    TOTAL_DURATION_MINUTES  NUMBER(16,4),
    ERROR_COUNT             NUMBER(10)      DEFAULT 0 NOT NULL,
    SAMPLE_LOG_ID           NUMBER(19),
    SAMPLE_QUERY_SEQ_ID     NUMBER(19),
    SAMPLE_QUERY            CLOB,
    NORMALIZED_QUERY        CLOB,
    ROW_INDICES             CLOB,
    FIRST_SEEN              TIMESTAMP,
    LAST_SEEN               TIMESTAMP,
    CREATED_AT              TIMESTAMP       NOT NULL,
    UPDATED_AT              TIMESTAMP,
    VERSION                 NUMBER(10)      DEFAULT 0 NOT NULL,
    CONSTRAINT PK_SPT_QUERY_GROUP PRIMARY KEY (ID),
    CONSTRAINT UK_SPT_GROUP_FP UNIQUE (SQL_ENGINE, FINGERPRINT)
);
COMMENT ON TABLE SPT_QUERY_GROUP IS 'Query groups: log rows with the same SQL ignoring WHERE filters.';
COMMENT ON COLUMN SPT_QUERY_GROUP.FINGERPRINT IS 'SHA-256 of the normalized SQL (comments, literals and WHERE clauses removed).';
COMMENT ON COLUMN SPT_QUERY_GROUP.ROW_INDICES IS 'Comma separated SEQ_IDs of the member log rows.';
COMMENT ON COLUMN SPT_QUERY_GROUP.SAMPLE_LOG_ID IS 'Longest running member - the "bad SQL" candidate.';
CREATE INDEX IX_SPT_GROUP_TOTAL_DUR ON SPT_QUERY_GROUP (TOTAL_DURATION_MINUTES);
CREATE INDEX IX_SPT_GROUP_FIRST_SEEN ON SPT_QUERY_GROUP (FIRST_SEEN);

-- ---------------------------------------------------------------------
-- Raw query log rows (input file / source table); each row is processed once
-- ---------------------------------------------------------------------
CREATE TABLE SPT_QUERY_LOG (
    ID                  NUMBER(19)      GENERATED BY DEFAULT AS IDENTITY,
    BATCH_ID            NUMBER(19)      NOT NULL,
    SEQ_ID              NUMBER(19),
    EXECUTED_QUERY      CLOB,
    USER_QUERY          CLOB,
    ERROR_CODE          VARCHAR2(100),
    ERROR_CATEGORY      VARCHAR2(200),
    ERROR_MESSAGE       CLOB,
    USER_ID             VARCHAR2(200),
    START_TIME          TIMESTAMP,
    END_TIME            TIMESTAMP,
    DURATION_MINUTES    NUMBER(14,4),
    SQL_ENGINE          VARCHAR2(20)    NOT NULL,
    FINGERPRINT         VARCHAR2(64),
    GROUP_ID            NUMBER(19),
    ROW_KEY             VARCHAR2(64),
    SEEN_COUNT          NUMBER(10)      DEFAULT 1 NOT NULL,
    LAST_SEEN_AT        TIMESTAMP,
    LAST_SEEN_BATCH_ID  NUMBER(19),
    CREATED_AT          TIMESTAMP       NOT NULL,
    CONSTRAINT PK_SPT_QUERY_LOG PRIMARY KEY (ID),
    CONSTRAINT FK_SPT_LOG_BATCH FOREIGN KEY (BATCH_ID) REFERENCES SPT_INGESTION_BATCH (ID),
    CONSTRAINT FK_SPT_LOG_GROUP FOREIGN KEY (GROUP_ID) REFERENCES SPT_QUERY_GROUP (ID)
);
COMMENT ON TABLE SPT_QUERY_LOG IS 'Query log rows (seq_id, executed_query, user_query, errors, user, start/end time, duration).';
COMMENT ON COLUMN SPT_QUERY_LOG.ROW_KEY IS 'SHA-256 identity of the log row (see spt.ingestion.row-identity). Rows with an existing key are never re-processed.';
COMMENT ON COLUMN SPT_QUERY_LOG.SEEN_COUNT IS 'Number of loads the row appeared in.';
CREATE INDEX IX_SPT_LOG_GROUP ON SPT_QUERY_LOG (GROUP_ID);
CREATE INDEX IX_SPT_LOG_FP ON SPT_QUERY_LOG (SQL_ENGINE, FINGERPRINT);
CREATE INDEX IX_SPT_LOG_BATCH ON SPT_QUERY_LOG (BATCH_ID);
CREATE INDEX IX_SPT_LOG_USER ON SPT_QUERY_LOG (USER_ID);
CREATE INDEX IX_SPT_LOG_START ON SPT_QUERY_LOG (START_TIME);
CREATE INDEX IX_SPT_LOG_SEQ ON SPT_QUERY_LOG (SEQ_ID);
CREATE UNIQUE INDEX UX_SPT_LOG_ROW_KEY ON SPT_QUERY_LOG (ROW_KEY);

-- ---------------------------------------------------------------------
-- Load history: one row per (log row, load)
-- ---------------------------------------------------------------------
CREATE TABLE SPT_QUERY_LOG_SIGHTING (
    ID          NUMBER(19)  GENERATED BY DEFAULT AS IDENTITY,
    LOG_ID      NUMBER(19)  NOT NULL,
    BATCH_ID    NUMBER(19)  NOT NULL,
    SEEN_AT     TIMESTAMP   NOT NULL,
    IS_FIRST    NUMBER(1)   DEFAULT 0 NOT NULL,
    CONSTRAINT PK_SPT_QUERY_LOG_SIGHTING PRIMARY KEY (ID),
    CONSTRAINT UK_SPT_SIGHTING UNIQUE (LOG_ID, BATCH_ID),
    CONSTRAINT FK_SPT_SIGHT_LOG FOREIGN KEY (LOG_ID) REFERENCES SPT_QUERY_LOG (ID),
    CONSTRAINT FK_SPT_SIGHT_BATCH FOREIGN KEY (BATCH_ID) REFERENCES SPT_INGESTION_BATCH (ID),
    CONSTRAINT CK_SPT_SIGHT_FIRST CHECK (IS_FIRST IN (0, 1))
);
CREATE INDEX IX_SPT_SIGHT_BATCH ON SPT_QUERY_LOG_SIGHTING (BATCH_ID);

-- ---------------------------------------------------------------------
-- Tuning tracker: one row per group being worked on
-- (group metrics are read live from SPT_QUERY_GROUP, see SPT_TRACKER_V)
-- ---------------------------------------------------------------------
CREATE TABLE SPT_TUNING_TRACKER (
    ID                              NUMBER(19)      GENERATED BY DEFAULT AS IDENTITY,
    GROUP_ID                        NUMBER(19)      NOT NULL,
    WORKFLOW_STATUS                 VARCHAR2(40)    DEFAULT 'NEW' NOT NULL,
    PRIORITY                        VARCHAR2(20)    DEFAULT 'MEDIUM' NOT NULL,
    REQUEST_SOURCE                  VARCHAR2(30)    DEFAULT 'LOG_DETECTED' NOT NULL,
    REQUESTED_BY                    VARCHAR2(200),
    ENVIRONMENT                     VARCHAR2(30),
    SAMPLE_QUERY_FORMATTED          CLOB,
    CLEANSED_QUERY                  CLOB,
    OPTIMIZED_QUERY                 CLOB,
    SELECTED_ITERATION_ID           NUMBER(19),
    DEV_TEAM_LEAD                   VARCHAR2(200),
    DEV_TEAM_STATUS                 VARCHAR2(100),
    CLOUDERA_TEAM_LEAD              VARCHAR2(200),
    SME_TEAM_LEAD                   VARCHAR2(200),
    OPTIMIZED_SQL_STATUS            VARCHAR2(100),
    CLOUDERA_POST_RUN_VALIDATION    VARCHAR2(100),
    OG_RUN_DURATION_MINUTES         NUMBER(14,4),
    POST_RUN_DURATION_MINUTES       NUMBER(14,4),
    OG_EXECUTION_TIME_SECONDS       NUMBER(14,4),
    POST_RUN_EXECUTION_TIME_SECONDS NUMBER(14,4),
    OG_TEARDOWN_TIME_SECONDS        NUMBER(14,4),
    POST_RUN_TEARDOWN_TIME_SECONDS  NUMBER(14,4),
    OG_TEARDOWN_PCT                 NUMBER(7,3),
    POST_RUN_TEARDOWN_PCT           NUMBER(7,3),
    OG_CPU_SECONDS                  NUMBER(16,4),
    POST_RUN_CPU_SECONDS            NUMBER(16,4),
    OG_ROWS_SCANNED                 NUMBER(19),
    POST_RUN_ROWS_SCANNED           NUMBER(19),
    OG_TABLES_SCANNED               NUMBER(10),
    POST_RUN_TABLES_SCANNED         NUMBER(10),
    OG_BYTES_SCANNED                NUMBER(19),
    POST_RUN_BYTES_SCANNED          NUMBER(19),
    OG_PEAK_MEMORY_MB               NUMBER(14,2),
    POST_RUN_PEAK_MEMORY_MB         NUMBER(14,2),
    THEME                           VARCHAR2(200),
    SME_VALIDATION                  VARCHAR2(100),
    INSTALL_STATUS                  VARCHAR2(100),
    EXECUTE_STATUS                  VARCHAR2(100),
    VALIDATION_STATUS               VARCHAR2(100),
    CHANGES                         CLOB,
    PROBLEM                         CLOB,
    RECOMMENDATIONS                 CLOB,
    STAGE_CHANGED_AT                TIMESTAMP,
    ADOPTED_AT                      TIMESTAMP,
    CLOSED_AT                       TIMESTAMP,
    CREATED_AT                      TIMESTAMP       NOT NULL,
    CREATED_BY                      VARCHAR2(100),
    UPDATED_AT                      TIMESTAMP,
    UPDATED_BY                      VARCHAR2(100),
    VERSION                         NUMBER(10)      DEFAULT 0 NOT NULL,
    CONSTRAINT PK_SPT_TUNING_TRACKER PRIMARY KEY (ID),
    CONSTRAINT UK_SPT_TRACKER_GROUP UNIQUE (GROUP_ID),
    CONSTRAINT FK_SPT_TRACKER_GROUP FOREIGN KEY (GROUP_ID) REFERENCES SPT_QUERY_GROUP (ID),
    CONSTRAINT CK_SPT_TRACKER_PRIORITY CHECK (PRIORITY IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    CONSTRAINT CK_SPT_TRACKER_SOURCE CHECK (REQUEST_SOURCE IN ('LOG_DETECTED', 'PROACTIVE_UAT', 'USER_REQUEST'))
);
COMMENT ON TABLE SPT_TUNING_TRACKER IS 'Tuning tracker: one item per query group being tuned, from triage to adoption.';
COMMENT ON COLUMN SPT_TUNING_TRACKER.WORKFLOW_STATUS IS 'Stage: NEW, DIAGNOSTICS_CAPTURED, OPTIMIZATION_REQUESTED, OPTIMIZED, POST_RUN_VALIDATED, SME_VALIDATION, ADOPTED, REJECTED, ON_HOLD.';
COMMENT ON COLUMN SPT_TUNING_TRACKER.STAGE_CHANGED_AT IS 'When the item entered its current stage.';
COMMENT ON COLUMN SPT_TUNING_TRACKER.SELECTED_ITERATION_ID IS 'Iteration selected for adoption; its SQL and post-run metrics are copied here.';
CREATE INDEX IX_SPT_TRACKER_STATUS ON SPT_TUNING_TRACKER (WORKFLOW_STATUS);
CREATE INDEX IX_SPT_TRACKER_ADOPTED ON SPT_TUNING_TRACKER (ADOPTED_AT);
CREATE INDEX IX_SPT_TRACKER_THEME ON SPT_TUNING_TRACKER (THEME);

-- ---------------------------------------------------------------------
-- Optimization agent: versioned prompts and runs
-- ---------------------------------------------------------------------
CREATE TABLE SPT_PROMPT_TEMPLATE (
    ID              NUMBER(19)      GENERATED BY DEFAULT AS IDENTITY,
    NAME            VARCHAR2(100)   NOT NULL,
    SQL_ENGINE      VARCHAR2(20)    NOT NULL,
    VERSION_NO      NUMBER(5)       NOT NULL,
    TEMPLATE_TEXT   CLOB            NOT NULL,
    ACTIVE          NUMBER(1)       DEFAULT 1 NOT NULL,
    NOTES           VARCHAR2(2000),
    CREATED_AT      TIMESTAMP       NOT NULL,
    CREATED_BY      VARCHAR2(100),
    CONSTRAINT PK_SPT_PROMPT_TEMPLATE PRIMARY KEY (ID),
    CONSTRAINT UK_SPT_PROMPT_VER UNIQUE (NAME, VERSION_NO),
    CONSTRAINT CK_SPT_PROMPT_ACTIVE CHECK (ACTIVE IN (0, 1))
);

CREATE TABLE SPT_OPTIMIZATION_RUN (
    ID                  NUMBER(19)      GENERATED BY DEFAULT AS IDENTITY,
    GROUP_ID            NUMBER(19)      NOT NULL,
    PROMPT_TEMPLATE_ID  NUMBER(19),
    MODEL_NAME          VARCHAR2(100),
    PROMPT_TEXT         CLOB,
    RESPONSE_RAW        CLOB,
    CHANGE_NARRATIVE    CLOB,
    OPTIMIZED_SQL       CLOB,
    STATUS              VARCHAR2(20)    NOT NULL,
    OUTCOME             VARCHAR2(20),
    ERROR_MESSAGE       CLOB,
    REQUESTED_AT        TIMESTAMP       NOT NULL,
    COMPLETED_AT        TIMESTAMP,
    REQUESTED_BY        VARCHAR2(100),
    CONSTRAINT PK_SPT_OPTIMIZATION_RUN PRIMARY KEY (ID),
    CONSTRAINT FK_SPT_OPT_GROUP FOREIGN KEY (GROUP_ID) REFERENCES SPT_QUERY_GROUP (ID),
    CONSTRAINT FK_SPT_OPT_PROMPT FOREIGN KEY (PROMPT_TEMPLATE_ID) REFERENCES SPT_PROMPT_TEMPLATE (ID),
    CONSTRAINT CK_SPT_OPT_STATUS CHECK (STATUS IN ('PENDING', 'COMPLETED', 'FAILED')),
    CONSTRAINT CK_SPT_OPT_OUTCOME CHECK (OUTCOME IS NULL OR OUTCOME IN ('ACCEPTED', 'REJECTED'))
);
CREATE INDEX IX_SPT_OPT_GROUP ON SPT_OPTIMIZATION_RUN (GROUP_ID);

-- ---------------------------------------------------------------------
-- Tuning iterations: every attempt with its test results; the best one is
-- selected, then adopted or rejected
-- ---------------------------------------------------------------------
CREATE TABLE SPT_TUNING_ITERATION (
    ID                      NUMBER(19)      GENERATED BY DEFAULT AS IDENTITY,
    TRACKER_ID              NUMBER(19)      NOT NULL,
    ITERATION_NO            NUMBER(5)       NOT NULL,
    SOURCE                  VARCHAR2(20)    NOT NULL,
    OPTIMIZATION_RUN_ID     NUMBER(19),
    OPTIMIZED_SQL           CLOB,
    CHANGE_NARRATIVE        CLOB,
    STATUS                  VARCHAR2(20)    NOT NULL,
    RUN_DURATION_MINUTES    NUMBER(14,4),
    EXECUTION_TIME_SECONDS  NUMBER(14,4),
    TEARDOWN_TIME_SECONDS   NUMBER(14,4),
    CPU_SECONDS             NUMBER(16,4),
    ROWS_SCANNED            NUMBER(19),
    BYTES_SCANNED           NUMBER(19),
    TABLES_SCANNED          NUMBER(10),
    PEAK_MEMORY_MB          NUMBER(14,2),
    RESULT_ROW_COUNT        NUMBER(19),
    RESULT_MATCHES          NUMBER(1),
    NOTES                   CLOB,
    TESTED_AT               TIMESTAMP,
    TESTED_BY               VARCHAR2(100),
    CREATED_AT              TIMESTAMP       NOT NULL,
    CREATED_BY              VARCHAR2(100),
    UPDATED_AT              TIMESTAMP,
    VERSION                 NUMBER(10)      DEFAULT 0 NOT NULL,
    CONSTRAINT PK_SPT_TUNING_ITERATION PRIMARY KEY (ID),
    CONSTRAINT UK_SPT_ITERATION_NO UNIQUE (TRACKER_ID, ITERATION_NO),
    CONSTRAINT FK_SPT_ITER_TRACKER FOREIGN KEY (TRACKER_ID) REFERENCES SPT_TUNING_TRACKER (ID),
    CONSTRAINT FK_SPT_ITER_RUN FOREIGN KEY (OPTIMIZATION_RUN_ID) REFERENCES SPT_OPTIMIZATION_RUN (ID),
    CONSTRAINT CK_SPT_ITER_SOURCE CHECK (SOURCE IN ('AI_AGENT', 'MANUAL')),
    CONSTRAINT CK_SPT_ITER_STATUS CHECK (STATUS IN ('PROPOSED', 'TESTED', 'FAILED', 'SELECTED', 'ADOPTED', 'REJECTED')),
    CONSTRAINT CK_SPT_ITER_MATCH CHECK (RESULT_MATCHES IS NULL OR RESULT_MATCHES IN (0, 1))
);
COMMENT ON TABLE SPT_TUNING_ITERATION IS 'Tuning attempts per tracker item with test metrics (PROPOSED -> TESTED -> SELECTED -> ADOPTED / REJECTED).';
CREATE INDEX IX_SPT_ITER_TRACKER ON SPT_TUNING_ITERATION (TRACKER_ID);

ALTER TABLE SPT_TUNING_TRACKER ADD CONSTRAINT FK_SPT_TRACKER_ITER
    FOREIGN KEY (SELECTED_ITERATION_ID) REFERENCES SPT_TUNING_ITERATION (ID);

-- ---------------------------------------------------------------------
-- Diagnostics captured by the SQL Diagnostic Tool (before / after)
-- ---------------------------------------------------------------------
CREATE TABLE SPT_SQL_DIAGNOSTIC (
    ID                      NUMBER(19)      GENERATED BY DEFAULT AS IDENTITY,
    GROUP_ID                NUMBER(19)      NOT NULL,
    PHASE                   VARCHAR2(20)    NOT NULL,
    OPTIMIZATION_RUN_ID     NUMBER(19),
    ITERATION_ID            NUMBER(19),
    QUERY_ID                VARCHAR2(100),
    SQL_TEXT                CLOB,
    ROW_COUNT               NUMBER(19),
    RUN_DURATION_SECONDS    NUMBER(14,4),
    EXECUTION_TIME_SECONDS  NUMBER(14,4),
    TEARDOWN_TIME_SECONDS   NUMBER(14,4),
    CPU_SECONDS             NUMBER(16,4),
    ROWS_SCANNED            NUMBER(19),
    BYTES_SCANNED           NUMBER(19),
    TABLES_SCANNED          NUMBER(10),
    PEAK_MEMORY_MB          NUMBER(14,2),
    EXPLAIN_PLAN            CLOB,
    PROFILE_RAW             CLOB,
    PROFILE_SUMMARY         CLOB,
    EXEC_SUMMARY            CLOB,
    STATUS                  VARCHAR2(20)    NOT NULL,
    ERROR_MESSAGE           CLOB,
    CAPTURED_AT             TIMESTAMP       NOT NULL,
    CAPTURED_BY             VARCHAR2(100),
    CONSTRAINT PK_SPT_SQL_DIAGNOSTIC PRIMARY KEY (ID),
    CONSTRAINT FK_SPT_DIAG_GROUP FOREIGN KEY (GROUP_ID) REFERENCES SPT_QUERY_GROUP (ID),
    CONSTRAINT FK_SPT_DIAG_OPT FOREIGN KEY (OPTIMIZATION_RUN_ID) REFERENCES SPT_OPTIMIZATION_RUN (ID),
    CONSTRAINT FK_SPT_DIAG_ITER FOREIGN KEY (ITERATION_ID) REFERENCES SPT_TUNING_ITERATION (ID),
    CONSTRAINT CK_SPT_DIAG_PHASE CHECK (PHASE IN ('ORIGINAL', 'OPTIMIZED')),
    CONSTRAINT CK_SPT_DIAG_STATUS CHECK (STATUS IN ('CAPTURED', 'FAILED', 'TIMEOUT'))
);
COMMENT ON COLUMN SPT_SQL_DIAGNOSTIC.PROFILE_SUMMARY IS 'JSON produced by the profile parser (step 6) - compact input for the LLM.';
CREATE INDEX IX_SPT_DIAG_GROUP ON SPT_SQL_DIAGNOSTIC (GROUP_ID, PHASE);

CREATE TABLE SPT_TABLE_DDL (
    ID          NUMBER(19)      GENERATED BY DEFAULT AS IDENTITY,
    GROUP_ID    NUMBER(19)      NOT NULL,
    TABLE_NAME  VARCHAR2(300)   NOT NULL,
    DDL_TEXT    CLOB,
    ROW_COUNT   NUMBER(19),
    CAPTURED_AT TIMESTAMP       NOT NULL,
    CAPTURED_BY VARCHAR2(100),
    CONSTRAINT PK_SPT_TABLE_DDL PRIMARY KEY (ID),
    CONSTRAINT FK_SPT_DDL_GROUP FOREIGN KEY (GROUP_ID) REFERENCES SPT_QUERY_GROUP (ID)
);
CREATE INDEX IX_SPT_DDL_GROUP ON SPT_TABLE_DDL (GROUP_ID);

-- ---------------------------------------------------------------------
-- Adoption / rejection feedback (diagram step 12 + failed optimization note)
-- ---------------------------------------------------------------------
CREATE TABLE SPT_FEEDBACK (
    ID                  NUMBER(19)      GENERATED BY DEFAULT AS IDENTITY,
    GROUP_ID            NUMBER(19)      NOT NULL,
    OPTIMIZATION_RUN_ID NUMBER(19),
    ITERATION_ID        NUMBER(19),
    SOURCE_ROLE         VARCHAR2(30)    NOT NULL,
    DECISION            VARCHAR2(20)    NOT NULL,
    REJECTION_REASON    VARCHAR2(200),
    COMMENTS            CLOB,
    CREATED_AT          TIMESTAMP       NOT NULL,
    CREATED_BY          VARCHAR2(100),
    CONSTRAINT PK_SPT_FEEDBACK PRIMARY KEY (ID),
    CONSTRAINT FK_SPT_FB_GROUP FOREIGN KEY (GROUP_ID) REFERENCES SPT_QUERY_GROUP (ID),
    CONSTRAINT FK_SPT_FB_OPT FOREIGN KEY (OPTIMIZATION_RUN_ID) REFERENCES SPT_OPTIMIZATION_RUN (ID),
    CONSTRAINT FK_SPT_FB_ITER FOREIGN KEY (ITERATION_ID) REFERENCES SPT_TUNING_ITERATION (ID),
    CONSTRAINT CK_SPT_FB_ROLE CHECK (SOURCE_ROLE IN ('BUSINESS_USER', 'CLIENT_DEV', 'CLOUDERA', 'SME')),
    CONSTRAINT CK_SPT_FB_DECISION CHECK (DECISION IN ('ADOPTED', 'REJECTED', 'COMMENT'))
);
CREATE INDEX IX_SPT_FB_GROUP ON SPT_FEEDBACK (GROUP_ID);

-- ---------------------------------------------------------------------
-- Runtime-extensible columns
-- ---------------------------------------------------------------------
CREATE TABLE SPT_CUSTOM_FIELD (
    ID              NUMBER(19)      GENERATED BY DEFAULT AS IDENTITY,
    ENTITY_TYPE     VARCHAR2(30)    NOT NULL,
    FIELD_KEY       VARCHAR2(100)   NOT NULL,
    LABEL           VARCHAR2(200)   NOT NULL,
    DATA_TYPE       VARCHAR2(20)    NOT NULL,
    OPTIONS_CSV     VARCHAR2(4000),
    DISPLAY_ORDER   NUMBER(5)       DEFAULT 0 NOT NULL,
    REQUIRED        NUMBER(1)       DEFAULT 0 NOT NULL,
    ACTIVE          NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATED_AT      TIMESTAMP       NOT NULL,
    CREATED_BY      VARCHAR2(100),
    CONSTRAINT PK_SPT_CUSTOM_FIELD PRIMARY KEY (ID),
    CONSTRAINT UK_SPT_CF_KEY UNIQUE (ENTITY_TYPE, FIELD_KEY),
    CONSTRAINT CK_SPT_CF_ENTITY CHECK (ENTITY_TYPE IN ('TRACKER', 'GROUP', 'LOG')),
    CONSTRAINT CK_SPT_CF_TYPE CHECK (DATA_TYPE IN ('TEXT', 'LONG_TEXT', 'NUMBER', 'DATE', 'BOOLEAN', 'ENUM'))
);

CREATE TABLE SPT_CUSTOM_FIELD_VALUE (
    ID          NUMBER(19)      GENERATED BY DEFAULT AS IDENTITY,
    FIELD_ID    NUMBER(19)      NOT NULL,
    ENTITY_ID   NUMBER(19)      NOT NULL,
    VALUE_TEXT  VARCHAR2(4000),
    UPDATED_AT  TIMESTAMP       NOT NULL,
    UPDATED_BY  VARCHAR2(100),
    CONSTRAINT PK_SPT_CUSTOM_FIELD_VALUE PRIMARY KEY (ID),
    CONSTRAINT UK_SPT_CFV UNIQUE (FIELD_ID, ENTITY_ID),
    CONSTRAINT FK_SPT_CFV_FIELD FOREIGN KEY (FIELD_ID) REFERENCES SPT_CUSTOM_FIELD (ID) ON DELETE CASCADE
);
CREATE INDEX IX_SPT_CFV_ENTITY ON SPT_CUSTOM_FIELD_VALUE (ENTITY_ID);

-- ---------------------------------------------------------------------
-- Field-level change history (tracker edits, stage changes)
-- ---------------------------------------------------------------------
CREATE TABLE SPT_AUDIT_EVENT (
    ID          NUMBER(19)      GENERATED BY DEFAULT AS IDENTITY,
    ENTITY_TYPE VARCHAR2(30)    NOT NULL,
    ENTITY_ID   NUMBER(19)      NOT NULL,
    ACTION      VARCHAR2(20)    NOT NULL,
    FIELD_NAME  VARCHAR2(100),
    OLD_VALUE   VARCHAR2(4000),
    NEW_VALUE   VARCHAR2(4000),
    CHANGED_AT  TIMESTAMP       NOT NULL,
    CHANGED_BY  VARCHAR2(100),
    CONSTRAINT PK_SPT_AUDIT_EVENT PRIMARY KEY (ID)
);
CREATE INDEX IX_SPT_AUDIT_ENTITY ON SPT_AUDIT_EVENT (ENTITY_TYPE, ENTITY_ID);

-- ---------------------------------------------------------------------
-- Dropdown values (Administration -> Dropdown values)
-- ---------------------------------------------------------------------
CREATE TABLE SPT_LOOKUP (
    ID              NUMBER(19)      GENERATED BY DEFAULT AS IDENTITY,
    CATEGORY        VARCHAR2(50)    NOT NULL,
    LOOKUP_VALUE    VARCHAR2(200)   NOT NULL,
    SORT_ORDER      NUMBER(5)       DEFAULT 0 NOT NULL,
    TONE            VARCHAR2(20),
    ACTIVE          NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATED_AT      TIMESTAMP       NOT NULL,
    CONSTRAINT PK_SPT_LOOKUP PRIMARY KEY (ID),
    CONSTRAINT UK_SPT_LOOKUP UNIQUE (CATEGORY, LOOKUP_VALUE),
    CONSTRAINT CK_SPT_LOOKUP_ACTIVE CHECK (ACTIVE IN (0, 1))
);
COMMENT ON COLUMN SPT_LOOKUP.TONE IS 'Chip colour hint for the UI: ok, warn, bad, info, muted.';

-- ---------------------------------------------------------------------
-- User directory: user id -> user group / department (Insights Q7, Q13)
-- ---------------------------------------------------------------------
CREATE TABLE SPT_USER_DIRECTORY (
    USER_ID         VARCHAR2(200)   NOT NULL,
    DISPLAY_NAME    VARCHAR2(200),
    USER_GROUP      VARCHAR2(200),
    DEPARTMENT      VARCHAR2(200),
    ACTIVE          NUMBER(1)       DEFAULT 1 NOT NULL,
    UPDATED_AT      TIMESTAMP       NOT NULL,
    UPDATED_BY      VARCHAR2(100),
    CONSTRAINT PK_SPT_USER_DIRECTORY PRIMARY KEY (USER_ID),
    CONSTRAINT CK_SPT_USERDIR_ACTIVE CHECK (ACTIVE IN (0, 1))
);
CREATE INDEX IX_SPT_USERDIR_GROUP ON SPT_USER_DIRECTORY (USER_GROUP);

-- =====================================================================
-- 3. VIEW: tracking screen = tracker + live group metrics
-- =====================================================================
CREATE OR REPLACE VIEW SPT_TRACKER_V AS
SELECT t.ID                         AS TRACKER_ID,
       g.ID                         AS GROUP_ID,
       g.GROUP_SIZE,
       g.DISTINCT_USERS,
       g.FINGERPRINT,
       g.AVG_DURATION_MINUTES,
       g.MIN_DURATION_MINUTES,
       g.MAX_DURATION_MINUTES,
       g.TOTAL_DURATION_MINUTES,
       g.FIRST_SEEN,
       g.LAST_SEEN,
       g.SAMPLE_QUERY_SEQ_ID,
       g.SAMPLE_QUERY               AS SAMPLE_QUERY_RAW,
       t.SAMPLE_QUERY_FORMATTED,
       g.ROW_INDICES,
       t.CLEANSED_QUERY,
       t.OPTIMIZED_QUERY,
       t.DEV_TEAM_LEAD,
       t.DEV_TEAM_STATUS,
       t.CLOUDERA_TEAM_LEAD,
       t.SME_TEAM_LEAD,
       t.OPTIMIZED_SQL_STATUS,
       t.CLOUDERA_POST_RUN_VALIDATION,
       t.OG_RUN_DURATION_MINUTES,
       t.POST_RUN_DURATION_MINUTES,
       t.OG_EXECUTION_TIME_SECONDS,
       t.POST_RUN_EXECUTION_TIME_SECONDS,
       t.OG_TEARDOWN_TIME_SECONDS,
       t.POST_RUN_TEARDOWN_TIME_SECONDS,
       t.OG_TEARDOWN_PCT,
       t.POST_RUN_TEARDOWN_PCT,
       t.OG_CPU_SECONDS,
       t.POST_RUN_CPU_SECONDS,
       t.OG_ROWS_SCANNED,
       t.POST_RUN_ROWS_SCANNED,
       t.OG_TABLES_SCANNED,
       t.POST_RUN_TABLES_SCANNED,
       t.THEME,
       t.SME_VALIDATION,
       t.INSTALL_STATUS,
       t.EXECUTE_STATUS,
       t.VALIDATION_STATUS,
       t.CHANGES,
       t.PROBLEM,
       t.RECOMMENDATIONS,
       t.WORKFLOW_STATUS,
       t.PRIORITY,
       t.REQUEST_SOURCE,
       t.REQUESTED_BY,
       t.ENVIRONMENT,
       t.SELECTED_ITERATION_ID,
       t.CREATED_AT,
       t.STAGE_CHANGED_AT,
       t.ADOPTED_AT,
       t.CLOSED_AT,
       t.UPDATED_AT,
       t.UPDATED_BY
  FROM SPT_TUNING_TRACKER t
  JOIN SPT_QUERY_GROUP g ON g.ID = t.GROUP_ID;

-- =====================================================================
-- 4. INITIAL VALUES
-- =====================================================================

-- ---------------------------------------------------------------------
-- Default Impala optimization prompt (diagram step 7).
-- {{placeholders}} are filled by the service (PromptRenderer).
-- ---------------------------------------------------------------------
INSERT INTO SPT_PROMPT_TEMPLATE (NAME, SQL_ENGINE, VERSION_NO, TEMPLATE_TEXT, ACTIVE, NOTES, CREATED_AT, CREATED_BY)
VALUES ('impala-default', 'IMPALA', 1, 'You are a senior Cloudera Impala performance engineer. Rewrite the SQL below so it returns exactly the same result set while running faster and using fewer cluster resources.

Consider: partition pruning, predicate push-down, join order and join strategy (BROADCAST vs SHUFFLE), missing or stale statistics (COMPUTE STATS), avoiding SELECT *, avoiding functions on partition columns, replacing correlated sub-queries, reducing data skew, and spilling to disk.

## Bad SQL
{{bad_sql}}

## Table DDL
{{ddl}}

## Table row counts
{{row_counts}}

## Explain plan
{{explain}}

## Parsed profile
{{profile_summary}}

## Execution summary
{{exec_summary}}

Respond with two sections exactly:
### CHANGE NARRATIVE
A numbered list of every change and why it helps.
### OPTIMIZED SQL
A single ```sql fenced block containing only the rewritten query.', 1, 'Initial prompt', SYSTIMESTAMP, 'system');

-- ---------------------------------------------------------------------
-- Dropdown values. Change them later in Administration -> Dropdown values.
-- TONE colours the chip: ok (green), warn (amber), bad (red), info (blue), muted (grey).
-- ---------------------------------------------------------------------
INSERT INTO SPT_LOOKUP (CATEGORY, LOOKUP_VALUE, SORT_ORDER, TONE, ACTIVE, CREATED_AT)
SELECT v.CATEGORY, v.LOOKUP_VALUE, v.SORT_ORDER, v.TONE, 1, SYSTIMESTAMP
  FROM (
    -- Theme / project the bad SQL belongs to (Insights Q4, Q11, Q12)
    SELECT 'THEME' CATEGORY, 'Partition pruning' LOOKUP_VALUE, 10 SORT_ORDER, 'info' TONE FROM DUAL UNION ALL
    SELECT 'THEME', 'Trade all', 20, 'info' FROM DUAL UNION ALL
    SELECT 'THEME', 'Teardown', 30, 'info' FROM DUAL UNION ALL
    SELECT 'THEME', 'Join strategy', 40, 'info' FROM DUAL UNION ALL
    SELECT 'THEME', 'Missing statistics', 50, 'info' FROM DUAL UNION ALL
    SELECT 'THEME', 'Data skew', 60, 'info' FROM DUAL UNION ALL
    SELECT 'THEME', 'Wide scans / SELECT *', 70, 'info' FROM DUAL UNION ALL
    SELECT 'THEME', 'Spill to disk', 80, 'info' FROM DUAL UNION ALL
    SELECT 'THEME', 'Small files', 90, 'info' FROM DUAL UNION ALL
    SELECT 'THEME', 'Complex views', 100, 'info' FROM DUAL UNION ALL
    SELECT 'THEME', 'Other', 110, 'muted' FROM DUAL UNION ALL
    -- Dev team status
    SELECT 'DEV_TEAM_STATUS', 'Not started', 10, 'muted' FROM DUAL UNION ALL
    SELECT 'DEV_TEAM_STATUS', 'In analysis', 20, 'info' FROM DUAL UNION ALL
    SELECT 'DEV_TEAM_STATUS', 'In progress', 30, 'info' FROM DUAL UNION ALL
    SELECT 'DEV_TEAM_STATUS', 'In review', 40, 'warn' FROM DUAL UNION ALL
    SELECT 'DEV_TEAM_STATUS', 'Blocked', 50, 'bad' FROM DUAL UNION ALL
    SELECT 'DEV_TEAM_STATUS', 'Done', 60, 'ok' FROM DUAL UNION ALL
    -- Optimized SQL
    SELECT 'OPTIMIZED_SQL_STATUS', 'Not started', 10, 'muted' FROM DUAL UNION ALL
    SELECT 'OPTIMIZED_SQL_STATUS', 'In progress', 20, 'info' FROM DUAL UNION ALL
    SELECT 'OPTIMIZED_SQL_STATUS', 'Candidate ready', 30, 'warn' FROM DUAL UNION ALL
    SELECT 'OPTIMIZED_SQL_STATUS', 'Validated', 40, 'ok' FROM DUAL UNION ALL
    SELECT 'OPTIMIZED_SQL_STATUS', 'Not possible', 50, 'bad' FROM DUAL UNION ALL
    -- Cloudera post-run validation
    SELECT 'CLOUDERA_POST_RUN_VALIDATION', 'Pending', 10, 'muted' FROM DUAL UNION ALL
    SELECT 'CLOUDERA_POST_RUN_VALIDATION', 'Passed', 20, 'ok' FROM DUAL UNION ALL
    SELECT 'CLOUDERA_POST_RUN_VALIDATION', 'Failed', 30, 'bad' FROM DUAL UNION ALL
    SELECT 'CLOUDERA_POST_RUN_VALIDATION', 'Not required', 40, 'muted' FROM DUAL UNION ALL
    -- SME validation
    SELECT 'SME_VALIDATION', 'Pending', 10, 'muted' FROM DUAL UNION ALL
    SELECT 'SME_VALIDATION', 'Approved', 20, 'ok' FROM DUAL UNION ALL
    SELECT 'SME_VALIDATION', 'Rejected', 30, 'bad' FROM DUAL UNION ALL
    SELECT 'SME_VALIDATION', 'Not required', 40, 'muted' FROM DUAL UNION ALL
    -- Install
    SELECT 'INSTALL_STATUS', 'Pending', 10, 'muted' FROM DUAL UNION ALL
    SELECT 'INSTALL_STATUS', 'Scheduled', 20, 'info' FROM DUAL UNION ALL
    SELECT 'INSTALL_STATUS', 'Installed', 30, 'ok' FROM DUAL UNION ALL
    SELECT 'INSTALL_STATUS', 'Rolled back', 40, 'bad' FROM DUAL UNION ALL
    SELECT 'INSTALL_STATUS', 'Not applicable', 50, 'muted' FROM DUAL UNION ALL
    -- Execute
    SELECT 'EXECUTE_STATUS', 'Pending', 10, 'muted' FROM DUAL UNION ALL
    SELECT 'EXECUTE_STATUS', 'Running', 20, 'info' FROM DUAL UNION ALL
    SELECT 'EXECUTE_STATUS', 'Succeeded', 30, 'ok' FROM DUAL UNION ALL
    SELECT 'EXECUTE_STATUS', 'Failed', 40, 'bad' FROM DUAL UNION ALL
    SELECT 'EXECUTE_STATUS', 'Not applicable', 50, 'muted' FROM DUAL UNION ALL
    -- Validation
    SELECT 'VALIDATION_STATUS', 'Pending', 10, 'muted' FROM DUAL UNION ALL
    SELECT 'VALIDATION_STATUS', 'Passed', 20, 'ok' FROM DUAL UNION ALL
    SELECT 'VALIDATION_STATUS', 'Failed', 30, 'bad' FROM DUAL UNION ALL
    SELECT 'VALIDATION_STATUS', 'Not applicable', 40, 'muted' FROM DUAL UNION ALL
    -- Environment the SQL runs in (proactive UAT tuning vs production, Q14)
    SELECT 'ENVIRONMENT', 'PROD', 10, 'info' FROM DUAL UNION ALL
    SELECT 'ENVIRONMENT', 'UAT', 20, 'info' FROM DUAL UNION ALL
    SELECT 'ENVIRONMENT', 'DEV', 30, 'info' FROM DUAL UNION ALL
    -- Why an optimization was rejected (Q15)
    SELECT 'REJECTION_REASON', 'Inaccurate results', 10, 'bad' FROM DUAL UNION ALL
    SELECT 'REJECTION_REASON', 'No performance gain', 20, 'warn' FROM DUAL UNION ALL
    SELECT 'REJECTION_REASON', 'Business logic changed', 30, 'warn' FROM DUAL UNION ALL
    SELECT 'REJECTION_REASON', 'Not feasible to deploy', 40, 'warn' FROM DUAL UNION ALL
    SELECT 'REJECTION_REASON', 'Other', 50, 'muted' FROM DUAL
  ) v;

-- ---------------------------------------------------------------------
-- Optional: example user groups (Insights Q7 / Q13). Replace with your users,
-- or upload a CSV in Administration -> Users & groups.
-- ---------------------------------------------------------------------
-- INSERT INTO SPT_USER_DIRECTORY (USER_ID, DISPLAY_NAME, USER_GROUP, DEPARTMENT, ACTIVE, UPDATED_AT, UPDATED_BY)
-- VALUES ('jsmith', 'J. Smith', 'Trading', 'Trading Technology', 1, SYSTIMESTAMP, 'dba');

-- ---------------------------------------------------------------------
-- Optional: an Impala log source (the password is read from the env variable named in PASSWORD_REF).
-- ---------------------------------------------------------------------
-- INSERT INTO SPT_DATA_SOURCE (NAME, SOURCE_TYPE, SQL_ENGINE, JDBC_URL, DRIVER_CLASS, USERNAME, PASSWORD_REF,
--                              LOG_QUERY, FETCH_SIZE, ACTIVE, DESCRIPTION, CREATED_AT, CREATED_BY)
-- VALUES ('impala-prod-logs', 'IMPALA', 'IMPALA', 'jdbc:impala://impala-host:21050/default;AuthMech=1',
--         'com.cloudera.impala.jdbc.Driver', 'svc_spt', 'SPT_IMPALA_PASSWORD',
--         'SELECT seq_id, executed_query, user_query, error_code, error_category, error_message, user_id,
--                 start_time, end_time, duration_minutes
--            FROM ops.bad_query_log WHERE start_time > :since',
--         1000, 0, 'Daily bad-query injection', SYSTIMESTAMP, 'dba');

COMMIT;

PROMPT
PROMPT SPT schema re-created. Rows loaded:
SELECT 'SPT_PROMPT_TEMPLATE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM SPT_PROMPT_TEMPLATE
UNION ALL
SELECT 'SPT_LOOKUP', COUNT(*) FROM SPT_LOOKUP;
